name: Bug or unexpected behaviour report
description: Create a report to help us find and fix bugs or improve behaviour
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: Please tell us what you were doing! You can include code and files by drag and dropping them into the text area.
      description: The more details we have the easier it is to understand the problem. Please include example code to reproduce the situation if possible. You can drop files in this text area.
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: What was the expected result?
    validations:
      required: true

  - type: textarea
    id: actual-result
    attributes:
      label: What was the actual result?
    validations:
      required: true      

  - type: dropdown
    id: os
    attributes:
      label: What operating system were you using?
      options:
        - Mac
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating system version
      description: What version of your operating system were you using?
      placeholder: macOS 10.13
    validations:
      required: true

  - type: input
    id: flucoma-version
    attributes:
      label: FluCoMa Version
      description: What version of the FluCoMa tools were you using?
      placeholder: 1.0.6
    validations:
      required: true
